### ISSUE TITLE
Wrong dropdown positioning

### ISSUE THREAD

**Issue by SpiffGreen** [Evavic44/rocketmeme#23]
Dropdown for `about` link on navbar is wrongly positioned.
This issue may be from the fact that it was developed and test only on a particular screen size and/or resolution.

**Comment by Evavic44** [comment]
What screen size did you test this with and can you post a screenshot of the issue? Thanks ✨

**Comment by SpiffGreen** [comment]
![Screenshot from 2022-03-08 18-12-17](https://user-images.githubusercontent.com/73044138/157867357-d5bd8587-7d42-47eb-bb32-9eab3be5391c.png)

Above is a screenshot of the bug displayed.
My screen resolution is 1920 x 1080 (16:9)

**Comment by Evavic44** [comment]
Lol, 😆 Yikes.... I'll fix this. Thanks for noticing it.
