### ISSUE TITLE
⭐ [Feat] - (Add user authentication) 

### ISSUE THREAD

**Issue by Evavic44** [Evavic44/rocketmeme#40]
**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
Add authentication so users can log in and save created memes and upload them.

**Additional context**
A small list of features needed to be implemented successfully before closing this issue.
- [x] Create a sign-in page 
- [ ] Redirect to the success page after a successful sign-in
- [ ] Login button changes to user profile on login
- [ ] Simple user modal on profile click

**Comment by LukasBrilla5** [comment]
Hello can you please assign this issue to me ?

**Comment by Evavic44** [comment]
> Hello can you please assign this issue to me ?

Hey, Lukas. Thanks for showing an interest in this project. We're no longer using clerk for authentication anymore. So this issue will have to be edited to fit the kind of authentication we want.
