### ISSUE TITLE
🔎 Add TypeSense 

### ISSUE THREAD

**Issue by Evavic44** [Evavic44/rocketmeme#57]
### Is your feature request related to a problem? Please describe.
Improve search experience of users

### Describe the solution you'd like
Add typesense to search for features like auto-complete, faster search, pagination, etc.

### Describe alternatives you've considered
None yet

**Comment by SpiffGreen** [comment]
We will look into it

**Comment by Evavic44** [comment]
@all-contributors please add @Evavic44 for maintenance, code, doc, and bug
