### ISSUE TITLE
Refactor onMouseLeave function

### ISSUE THREAD

**Issue by Evavic44** [Evavic44/rocketmeme#58]
## Issue
In the onMouseLeave function, the function called in the if statement is the same as the one in the else.

## Recommended Fix
Remove the conditional and put setDropdown(false).

## Source
https://github.com/Evavic44/rocketmeme/blob/eafed75491a6e419f62c9477c653b5ed52a49e6e/client/src/Components/Navbar.jsx#L16

**Comment by siddharth-kaushik** [comment]
Can I fix this?

**Comment by Evavic44** [comment]
> Can I fix this?

Hey, @siddharth-kaushik 🙂 Thanks, but someone has already made a PR for this issue, https://github.com/Evavic44/rocketmeme/pull/59. so sorry about that you can check out other issues in the repo if you like, if not keep an eye out for more issues soon.

Just in passing, in this repo, issues labeled with goodfirstissues do not require asking for permission before you can start working on it. But it's cool you did. Thank you.
