### ISSUE TITLE
Target hyperlinks to new or blank tab

### ISSUE THREAD

**Issue by amarealcoder** [Evavic44/rocketmeme#62]

**Comment by Evavic44** [comment]
Thanks for raising an issue, Amara. What Links are you referring?

**Comment by amarealcoder** [comment]
The BLOG and ABOUT from the dropdown navbar link to pages outside the app. I think it will be good to target the links to a blank page instead of having them open on the same page as the app.

**Comment by Evavic44** [comment]
The about is still on rocketmeme.com = https://rocketmeme.com/about

Here are the following links that need to be fixed
- [x] Blog
- [x] Documentation
- [x] License
- [x] Rocketmeme API

**Comment by amarealcoder** [comment]
I'm going to work on this now.

**Comment by Evavic44** [comment]
> I'm going to work on this now.

Looking forward to you PR.
