### ISSUE TITLE
Separate stylesheet 

### ISSUE THREAD

**Issue by SpiffGreen** [Evavic44/rocketmeme#9]
The styling is done internally with styled components. Separate the styling for different different pages as needed using a well structured approach.

**Comment by Evavic44** [comment]
What approach do you recommend? @SpiffGreen 🤔

**Comment by MorganJay** [comment]
@Evavic44  we could use something like this

<img width="190" alt="image" src="https://user-images.githubusercontent.com/32873262/161375642-d876ef3c-fff0-4440-8106-204b1506033f.png">

**Comment by Evavic44** [comment]
> @Evavic44 we could use something like this
> 
> <img alt="image" width="190" src="https://user-images.githubusercontent.com/32873262/161375642-d876ef3c-fff0-4440-8106-204b1506033f.png">

Hey @MorganJay. 👋🏽 Yes, this is the approach we opted for, though it was modified a bit.  has raised a PR for the files inside the [pages](https://github.com/Evavic44/rocketmeme/tree/refactor_styles/client/src/pages) directory.

The procedure @SpiffGreen did is to put each file in its respective folder and renamed it to index.js
For example, `About.jsx` is renamed to `index.jsx` and put inside an About folder and on the App.jsx, we can import it by pointing to the directory like so:

```js
import About from "./pages/About";
```

You can follow this procedure to minify the [components](https://github.com/Evavic44/rocketmeme/tree/main/client/src/Components) files.

**Comment by MorganJay** [comment]
Cool. I'll check it out
